"""email_validator.py — Corporate email validation utilities.

Provides is_corporate_email() to determine whether an email address belongs
to a corporate domain by rejecting known public and disposable providers.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Public / consumer email providers (~90 domains)
# ---------------------------------------------------------------------------
PUBLIC_EMAIL_DOMAINS: frozenset[str] = frozenset(
    {
        # Google
        "gmail.com",
        "googlemail.com",
        # Yahoo
        "yahoo.com",
        "yahoo.co.uk",
        "yahoo.co.in",
        "yahoo.co.jp",
        "yahoo.com.ar",
        "yahoo.com.au",
        "yahoo.com.br",
        "yahoo.com.mx",
        "yahoo.fr",
        "yahoo.de",
        "yahoo.it",
        "yahoo.es",
        "yahoo.ca",
        "ymail.com",
        "rocketmail.com",
        # Microsoft
        "hotmail.com",
        "hotmail.co.uk",
        "hotmail.fr",
        "hotmail.de",
        "hotmail.it",
        "hotmail.es",
        "hotmail.com.br",
        "hotmail.com.ar",
        "outlook.com",
        "outlook.fr",
        "outlook.de",
        "outlook.es",
        "outlook.it",
        "outlook.com.br",
        "live.com",
        "live.co.uk",
        "live.fr",
        "live.de",
        "live.com.ar",
        "live.com.mx",
        "msn.com",
        # Apple
        "icloud.com",
        "me.com",
        "mac.com",
        # AOL / Verizon Media
        "aol.com",
        "aol.co.uk",
        "aim.com",
        "verizon.net",
        "att.net",
        "sbcglobal.net",
        "bellsouth.net",
        "comcast.net",
        "charter.net",
        "cox.net",
        "earthlink.net",
        # ProtonMail
        "protonmail.com",
        "protonmail.ch",
        "proton.me",
        "pm.me",
        # Zoho (free tier)
        "zohomail.com",
        # Mail.com / GMX / Web.de / 1&1
        "mail.com",
        "email.com",
        "gmx.com",
        "gmx.net",
        "gmx.de",
        "gmx.at",
        "gmx.ch",
        "web.de",
        "freenet.de",
        # Russian / CIS
        "mail.ru",
        "yandex.com",
        "yandex.ru",
        "yandex.ua",
        "yandex.kz",
        "rambler.ru",
        "inbox.ru",
        "list.ru",
        "bk.ru",
        # Chinese
        "qq.com",
        "163.com",
        "126.com",
        "sina.com",
        "sina.cn",
        "sohu.com",
        "foxmail.com",
        # International / other popular free
        "tutanota.com",
        "tutamail.com",
        "tuta.io",
        "hushmail.com",
        "fastmail.com",
        "fastmail.fm",
        "lavabit.com",
        "rediffmail.com",
        "wp.pl",
        "op.pl",
        "interia.pl",
        "o2.pl",
        "t-online.de",
        "orange.fr",
        "free.fr",
        "laposte.net",
        "sfr.fr",
        "wanadoo.fr",
        "terra.com.br",
        "bol.com.br",
        "ig.com.br",
        "uol.com.br",
        "virgilio.it",
        "libero.it",
        "alice.it",
        "tiscali.it",
        "naver.com",
        "hanmail.net",
        "daum.net",
    }
)

# ---------------------------------------------------------------------------
# Disposable / temporary email domains (~150 domains)
# ---------------------------------------------------------------------------
DISPOSABLE_EMAIL_DOMAINS: frozenset[str] = frozenset(
    {
        # Classic disposables
        "mailinator.com",
        "guerrillamail.com",
        "guerrillamail.info",
        "guerrillamail.biz",
        "guerrillamail.de",
        "guerrillamail.net",
        "guerrillamail.org",
        "guerrillamailblock.com",
        "yopmail.com",
        "yopmail.fr",
        "cool.fr.nf",
        "jetable.fr.nf",
        "nospam.ze.tc",
        "nomail.xl.cx",
        "mega.zik.dj",
        "speed.1s.fr",
        "courriel.fr.nf",
        "moncourrier.fr.nf",
        "monemail.fr.nf",
        "monmail.fr.nf",
        "temp-mail.org",
        "temp-mail.io",
        "temp-mail.ru",
        "throwaway.email",
        "trashmail.com",
        "trashmail.at",
        "trashmail.io",
        "trashmail.me",
        "trashmail.net",
        "trashmail.org",
        "trashmail.xyz",
        "trashmail.de",
        "10minutemail.com",
        "10minutemail.net",
        "10minutemail.org",
        "10minutemail.co.za",
        "10minutemail.us",
        "10minemail.com",
        "10mail.org",
        "20minutemail.com",
        "20minutemail.it",
        "mohmal.com",
        "mailnull.com",
        "spamgourmet.com",
        "spamgourmet.org",
        "spamgourmet.net",
        "spambox.us",
        "spamfree24.org",
        "spamfree24.de",
        "spamfree24.eu",
        "spamfree24.info",
        "spamfree24.biz",
        "spamfree24.net",
        "spam.la",
        "spam4.me",
        "spaml.de",
        "spamspot.com",
        "mailnesia.com",
        "dispostable.com",
        "fakeinbox.com",
        "fakeinbox.info",
        "filzmail.com",
        "discard.email",
        "discardmail.com",
        "discardmail.de",
        "spambog.com",
        "spambog.de",
        "spambog.ru",
        "jetable.com",
        "jetable.net",
        "jetable.org",
        "jetable.fr",
        "jetable.pp.ua",
        "nospamfor.us",
        "nospamfor.com",
        "nospam.ze.tc",
        "mailnull.com",
        "mailnull.net",
        "getonemail.com",
        "getonemail.net",
        "maildrop.cc",
        "mailismagic.com",
        "mailme.lv",
        "mailme.gq",
        "mailme24.com",
        "mail-temporaire.fr",
        "mail-temporaire.com",
        "tempmail.com",
        "tempmail.net",
        "tempmail.org",
        "tempmail.de",
        "tempmail.us",
        "tempmail.eu",
        "tempmail.it",
        "temporaryemail.com",
        "temporaryemail.net",
        "temporaryemail.us",
        "temporaryinbox.com",
        "temporary-mail.net",
        "throwam.com",
        "throam.com",
        "throwam.com",
        "spamevader.com",
        "emkei.cz",
        "emailondeck.com",
        "e4ward.com",
        "emailias.com",
        "emailsensei.com",
        "emailtemporario.com.br",
        "fastacura.com",
        "fastchevy.com",
        "fastchrysler.com",
        "fastkawasaki.com",
        "fastmazda.com",
        "fastmitsubishi.com",
        "fastnissan.com",
        "fastpontiac.com",
        "fastsuzuki.com",
        "fasttoyota.com",
        "fastyamaha.com",
        "gbd.com",
        "gishpuppy.com",
        "gustr.com",
        "hatespam.org",
        "herp.in",
        "hidemail.de",
        "hmamail.com",
        "inboxalias.com",
        "inboxclean.com",
        "inboxclean.org",
        "iroid.com",
        "kasmail.com",
        "klassmaster.com",
        "klassmaster.net",
        "lol.ovpn.to",
        "lookugly.com",
        "lopl.co.cc",
        "lortemail.dk",
        "lovemeleaveme.com",
        "lr78.com",
        "maileater.com",
        "mailexpire.com",
        "mailguard.me",
        "mailhazard.com",
        "mailhazard.us",
        "mailimate.com",
        "mailin8r.com",
        "mailinater.com",
        "mailinator.net",
        "mailinator.org",
        "mailinator2.com",
        "mailinator2.net",
        "mailincubator.com",
        "mailme.ir",
        "mailmoat.com",
        "mailnew.com",
        "mailnull.com",
        "mailscrap.com",
        "mailseal.de",
        "mailshell.com",
        "mailsiphon.com",
        "mailslite.com",
        "mailzilla.com",
        "mailzilla.org",
        "mbx.cc",
        "mega.zik.dj",
        "meltmail.com",
        "messagebeamer.de",
        "mezimages.net",
        "migumail.com",
        "mindless.com",
        "mintemail.com",
        "mobileninja.co.uk",
        "moburl.com",
        "mswork.ru",
        "mucincanon.com",
        "myalias.pw",
        "myblogos.com",
        "mycard.net.ua",
        "myfastmail.com",
        "mynetstore.de",
        "mypacks.net",
        "mypartyclip.de",
        "myphantomemail.com",
        "mysamp.de",
        "myspaceinc.com",
        "myspaceinc.net",
        "myspaceinc.org",
        "myspacepimpedup.com",
        "myspamless.com",
        "mytrashmail.com",
        "neomailbox.com",
        "nepwk.com",
        "nervmich.net",
        "nervtmich.net",
        "netmails.com",
        "netmails.net",
        "neverbox.com",
        "nice-4u.com",
        "nobulk.com",
        "noclickemail.com",
        "nogmailspam.info",
        "nomail.pw",
        "nomail.xl.cx",
        "nomail2me.com",
        "nomorespamemails.com",
        "nonspam.eu",
        "nonspammer.de",
        "noref.in",
        "nospam.ze.tc",
        "nospamthanks.info",
        "notmailinator.com",
        "nowmymail.com",
        "nowmymail.net",
        "nus.edu.sg-10minemail.com",
    }
)


def is_corporate_email(
    email: str,
    *,
    admin_email: str | None = None,
    extra_blocked: set[str] | frozenset[str] | None = None,
) -> tuple[bool, str | None]:
    """Check if an email is from a corporate domain.

    Returns (True, None) if corporate, or (False, reason) if rejected.
    Reasons: 'invalid_format', 'invalid_domain', 'public_domain',
             'disposable_domain'.
    """
    # 1. Basic format: non-empty and contains exactly one "@"
    if not email or "@" not in email:
        return False, "invalid_format"

    # 2. Admin bypass (case-insensitive)
    if admin_email is not None and email.strip().lower() == admin_email.strip().lower():
        return True, None

    # 3. Split on the last "@" to handle (unlikely) multiple @ signs gracefully
    local_part, _, domain = email.rpartition("@")
    domain = domain.strip().lower()
    local_part = local_part.strip()

    if not local_part or not domain:
        return False, "invalid_format"

    # 4. Domain must contain at least one "." (reject "user@localhost")
    if "." not in domain:
        return False, "invalid_domain"

    # 5. Public consumer domains
    if domain in PUBLIC_EMAIL_DOMAINS:
        return False, "public_domain"

    # 6. Disposable / temporary domains
    if domain in DISPOSABLE_EMAIL_DOMAINS:
        return False, "disposable_domain"

    # 7. Caller-supplied extra blocked domains
    if extra_blocked and domain in {d.lower() for d in extra_blocked}:
        return False, "disposable_domain"

    # 8. Passes all checks — treat as corporate
    return True, None
